import { AppState } from './types';

export const initialData: AppState = {
  hasNewDemande: false,
  clients: [
    {
      id: 'c1',
      nom: 'Marc Tremblay',
      telephone: '514-555-0101',
      email: 'marc.demo@example.com',
      derniereVisite: '8 août 2026',
    },
    {
      id: 'c2',
      nom: 'Alexandre Roy',
      telephone: '514-555-0102',
      email: 'alexandre.demo@example.com',
      derniereVisite: '2 août 2026',
    },
    {
      id: 'c3',
      nom: 'Samuel Gagnon',
      telephone: '438-555-0103',
      email: 'samuel.demo@example.com',
      derniereVisite: '31 juillet 2026',
    },
    {
      id: 'c4',
      nom: 'Julie Martin',
      telephone: '514-555-0104',
      email: 'julie.demo@example.com',
      derniereVisite: '15 juillet 2026',
    },
  ],
  vehicules: [
    {
      id: 'v1',
      clientId: 'c1',
      marque: 'BMW',
      modele: 'M4',
      annee: 2024,
      couleur: 'Noir',
    },
    {
      id: 'v2',
      clientId: 'c2',
      marque: 'Audi',
      modele: 'RS5',
      annee: 2023,
      couleur: 'Gris Nardo',
    },
    {
      id: 'v3',
      clientId: 'c3',
      marque: 'Tesla',
      modele: 'Model 3',
      annee: 2024,
      couleur: 'Blanc',
    },
    {
      id: 'v4',
      clientId: 'c4',
      marque: 'Audi',
      modele: 'Q5',
      annee: 2022,
      couleur: 'Blanc',
    },
  ],
  demandes: [
    {
      id: 'd1',
      clientId: 'c1',
      clientNom: 'Marc Tremblay',
      clientTelephone: '514-555-0101',
      clientEmail: 'marc.demo@example.com',
      vehiculeMarque: 'BMW',
      vehiculeModele: 'M4',
      vehiculeAnnee: 2024,
      vehiculeCouleur: 'Noir',
      service: 'PPF avant',
      message: 'Je voudrais protéger l\'avant de ma voiture contre les impacts de pierres.',
      photos: 4,
      ville: 'Laval',
      budget: '1 500 – 2 000 $',
      status: 'nouvelle',
      dateCreation: '2026-08-09',
    },
    {
      id: 'd2',
      clientId: 'c2',
      clientNom: 'Alexandre Roy',
      clientTelephone: '514-555-0102',
      clientEmail: 'alexandre.demo@example.com',
      vehiculeMarque: 'Audi',
      vehiculeModele: 'RS5',
      vehiculeAnnee: 2023,
      vehiculeCouleur: 'Gris Nardo',
      service: 'Céramique',
      message: 'Protection céramique complète pour mon RS5.',
      photos: 3,
      ville: 'Montréal',
      budget: '800 – 1 200 $',
      status: 'en_analyse',
      dateCreation: '2026-08-08',
    },
    {
      id: 'd3',
      clientId: 'c3',
      clientNom: 'Samuel Gagnon',
      clientTelephone: '438-555-0103',
      clientEmail: 'samuel.demo@example.com',
      vehiculeMarque: 'Tesla',
      vehiculeModele: 'Model 3',
      vehiculeAnnee: 2024,
      vehiculeCouleur: 'Blanc',
      service: 'Detailing',
      message: 'Detailing complet intérieur et extérieur.',
      photos: 2,
      ville: 'Longueuil',
      budget: '300 – 500 $',
      status: 'confirmee',
      dateCreation: '2026-08-07',
    },
  ],
  rendezVous: [
    {
      id: 'r1',
      clientId: 'c1',
      clientNom: 'Marc Tremblay',
      vehicule: 'BMW M4',
      service: 'PPF avant',
      date: '2026-08-04',
      heure: '09:00',
      status: 'confirme',
    },
    {
      id: 'r2',
      clientId: 'c2',
      clientNom: 'Alexandre Roy',
      vehicule: 'Audi RS5',
      service: 'Céramique',
      date: '2026-08-05',
      heure: '11:00',
      status: 'confirme',
    },
    {
      id: 'r3',
      clientId: 'c3',
      clientNom: 'Samuel Gagnon',
      vehicule: 'Tesla Model 3',
      service: 'Detailing',
      date: '2026-08-06',
      heure: '14:00',
      status: 'en_attente',
    },
    {
      id: 'r4',
      clientId: 'c4',
      clientNom: 'Julie Martin',
      vehicule: 'Audi Q5',
      service: 'Correction de peinture',
      date: '2026-08-07',
      heure: '10:00',
      status: 'confirme',
    },
    {
      id: 'r5',
      clientId: 'c1',
      clientNom: 'Marc Tremblay',
      vehicule: 'BMW M4',
      service: 'PPF',
      date: '2026-08-10',
      heure: '09:00',
      status: 'confirme',
    },
    {
      id: 'r6',
      clientId: 'c2',
      clientNom: 'Alexandre Roy',
      vehicule: 'Audi RS5',
      service: 'Céramique',
      date: '2026-08-11',
      heure: '11:00',
      status: 'en_attente',
    },
    {
      id: 'r7',
      clientId: 'c3',
      clientNom: 'Samuel Gagnon',
      vehicule: 'Tesla Model 3',
      service: 'Detailing',
      date: '2026-08-12',
      heure: '14:00',
      status: 'confirme',
    },
    {
      id: 'r8',
      clientId: 'c4',
      clientNom: 'Julie Martin',
      vehicule: 'Audi Q5',
      service: 'Vitres teintées',
      date: '2026-08-13',
      heure: '15:00',
      status: 'en_attente',
    },
    {
      id: 'r9',
      clientId: 'c1',
      clientNom: 'Marc Tremblay',
      vehicule: 'BMW M4',
      service: 'Céramique',
      date: '2026-08-14',
      heure: '10:00',
      status: 'en_attente',
    },
    {
      id: 'r10',
      clientId: 'c4',
      clientNom: 'Julie Martin',
      vehicule: 'Audi Q5',
      service: 'Detailing',
      date: '2026-08-15',
      heure: '13:00',
      status: 'confirme',
    },
    {
      id: 'r11',
      clientId: 'c2',
      clientNom: 'Alexandre Roy',
      vehicule: 'Audi RS5',
      service: 'PPF',
      date: '2026-08-18',
      heure: '09:00',
      status: 'confirme',
    },
    {
      id: 'r12',
      clientId: 'c3',
      clientNom: 'Samuel Gagnon',
      vehicule: 'Tesla Model 3',
      service: 'Céramique',
      date: '2026-08-19',
      heure: '11:00',
      status: 'en_attente',
    },
    {
      id: 'r13',
      clientId: 'c1',
      clientNom: 'Marc Tremblay',
      vehicule: 'BMW M4',
      service: 'Detailing',
      date: '2026-08-20',
      heure: '14:00',
      status: 'confirme',
    },
    {
      id: 'r14',
      clientId: 'c4',
      clientNom: 'Julie Martin',
      vehicule: 'Audi Q5',
      service: 'Céramique',
      date: '2026-08-22',
      heure: '10:00',
      status: 'en_attente',
    },
    {
      id: 'r15',
      clientId: 'c2',
      clientNom: 'Alexandre Roy',
      vehicule: 'Audi RS5',
      service: 'Detailing',
      date: '2026-08-25',
      heure: '09:00',
      status: 'confirme',
    },
    {
      id: 'r16',
      clientId: 'c3',
      clientNom: 'Samuel Gagnon',
      vehicule: 'Tesla Model 3',
      service: 'PPF avant',
      date: '2026-08-26',
      heure: '13:00',
      status: 'en_attente',
    },
    {
      id: 'r17',
      clientId: 'c1',
      clientNom: 'Marc Tremblay',
      vehicule: 'BMW M4',
      service: 'Correction de peinture',
      date: '2026-08-28',
      heure: '10:00',
      status: 'confirme',
    },
    {
      id: 'r18',
      clientId: 'c4',
      clientNom: 'Julie Martin',
      vehicule: 'Audi Q5',
      service: 'PPF',
      date: '2026-08-29',
      heure: '15:00',
      status: 'en_attente',
    },
  ],
  historique: [
    { id: 'h1', vehiculeId: 'v1', service: 'PPF avant', date: '8 août 2026', prix: 1850 },
    { id: 'h2', vehiculeId: 'v1', service: 'Céramique', date: '12 juin 2026', prix: 950 },
    { id: 'h3', vehiculeId: 'v2', service: 'Céramique', date: '2 août 2026', prix: 1100 },
    { id: 'h4', vehiculeId: 'v3', service: 'Detailing', date: '31 juillet 2026', prix: 450 },
    { id: 'h5', vehiculeId: 'v4', service: 'Correction de peinture', date: '15 juillet 2026', prix: 750 },
  ],
  factures: [
    {
      id: 'f1',
      numero: '1042',
      clientNom: 'Marc Tremblay',
      service: 'PPF avant',
      montant: 1850,
      status: 'payee',
      date: '8 août 2026',
    },
    {
      id: 'f2',
      numero: '1041',
      clientNom: 'Alexandre Roy',
      service: 'Céramique',
      montant: 1100,
      status: 'payee',
      date: '2 août 2026',
    },
    {
      id: 'f3',
      numero: '1040',
      clientNom: 'Samuel Gagnon',
      service: 'Detailing',
      montant: 450,
      status: 'payee',
      date: '31 juillet 2026',
    },
    {
      id: 'f4',
      numero: '1039',
      clientNom: 'Julie Martin',
      service: 'Correction de peinture',
      montant: 750,
      status: 'en_attente',
      date: '15 juillet 2026',
    },
  ],
};

export const stats = {
  demandesEnAttente: 12,
  rendezVousSemaine: 8,
  clientsActifs: 34,
  revenusMois: 3850,
};
